vault_path = "C:/Users/MountCD/Desktop/Obsidian"

[prompt]
system_prompt = "You are a helpful AI."
personal_prompt = "You have friendly maners and trying to help user in it's problem"

[talk]
enabled=true
model_id="prism-ml/bonsai-27b"
api_url="http://127.0.0.1:1234/v1/chat/completions"
api_key="sk-lm-r7AskycC:p368f0GMh9Nwup9EHWU5"

[worker]
enabled=true
model_id="google/gemma-4-e2b"
api_url="127.0.0.1:1234/chat/completions"
api_key=""

[audio]
enabled=true
model_id="google/gemma-4-e2b"
api_url="127.0.0.1:1234/chat/completions"
api_key=""