use serde::Deserialize;
use std::env;
use std::fs;
use std::io::Write;

#[derive(Debug, Deserialize, Clone)]
pub struct AgentConfig {
    pub enabled: bool,
    /// Агент по умолчанию: используется, когда в `POST /v1/chat/new`
    /// не передан `agent`. Не больше одного включённого агента с `main = true`.
    #[serde(default)]
    pub main: bool,
    pub model_id: String,
    pub api_url: String,
    pub api_key: String,
    pub personality_prompt: String,
    /// Таймаут одного запроса к апстриму в секундах (разным моделям
    /// нужно разное время). Дефолт — `DEFAULT_TIMEOUT_SECS`.
    #[serde(default = "default_timeout_secs")]
    pub timeout_secs: u64,
}

/// Дефолт для `timeout_secs`, если поле не задано в config.toml.
pub const DEFAULT_TIMEOUT_SECS: u64 = 120;

fn default_timeout_secs() -> u64 {
    DEFAULT_TIMEOUT_SECS
}
impl AgentConfig {
    /// Системный промпт чата: общий + личный, через пустую строку,
    /// чтобы многострочные промпты не слипались.
    pub fn merge_config(&self, shared: &str) -> String {
        format!("{}\n\n{}", shared, self.personality_prompt)
    }
}
#[derive(Debug, Deserialize, Clone)]
pub struct Config {
    pub autogenerated: bool,
    pub database_url: String,
    /// Адрес и порт HTTP-сервера (например, `0.0.0.0:11080`).
    /// `None` означает "использовать дефолт".
    pub http_bind: Option<String>,
    pub verbose: bool,
    pub shared_prompt: String,
    /// Сколько последних сообщений (без учёта системного промпта)
    /// отправлять модели. Ограничивает рост запроса на длинных чатах.
    #[serde(default = "default_history_limit")]
    pub history_limit: u32,
    pub agents: std::collections::HashMap<String, AgentConfig>,
}

impl Config {
    /// Ключ включённого агента с `main = true`, если такой есть.
    pub fn main_agent(&self) -> Option<&str> {
        self.agents
            .iter()
            .find(|(_, a)| a.enabled && a.main)
            .map(|(name, _)| name.as_str())
    }
}

/// Дефолт для `history_limit`, если поле не задано в config.toml.
pub const DEFAULT_HISTORY_LIMIT: u32 = 50;

fn default_history_limit() -> u32 {
    DEFAULT_HISTORY_LIMIT
}

/// Ошибки загрузки/парсинга конфигурации.
#[derive(Debug)]
pub enum ConfigError {
    Autogenerated,
    Io(std::io::Error),
    Parse(toml::de::Error),
    MissingField(&'static str),
    InvalidArgs(String),
    /// Конфиг разобран, но содержит противоречие.
    Invalid(String),
    /// Не удалось определить домашнюю директорию (нет `$HOME`).
    NoHomeDir,
}

impl std::fmt::Display for ConfigError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ConfigError::Autogenerated => write!(f, "Config is autogenerated. Redact it firstly."),
            ConfigError::Io(e) => write!(f, "failed to read config: {e}"),
            ConfigError::Parse(e) => write!(f, "failed to parse TOML: {e}"),
            ConfigError::MissingField(name) => write!(f, "missing field `{name}` in config"),
            ConfigError::InvalidArgs(msg) => write!(f, "{msg}"),
            ConfigError::Invalid(msg) => write!(f, "invalid config: {msg}"),
            ConfigError::NoHomeDir => write!(
                f,
                "cannot determine home directory; set $HOME or pass --config / {ENV_CONFIG}"
            ),
        }
    }
}

impl std::error::Error for ConfigError {}

/// Дефолтная директория конфигурации (`$HOME/.config/obscape`).
fn make_conf_path() -> Result<String, ConfigError> {
    let home = env::home_dir()
        .and_then(|h| h.into_os_string().into_string().ok())
        .ok_or(ConfigError::NoHomeDir)?;
    let out = format!("{home}/.config/obscape");
    Ok(out)
}

pub fn make_file_path() -> Result<String, ConfigError> {
    Ok(format!("{}/config.toml", make_conf_path()?))
}

pub fn format_conf_path(path: String) -> String {
    format!("{}/config.toml", path)
}

/// Дефолтный адрес HTTP-сервера.
const DEFAULT_HTTP_BIND: &str = "0.0.0.0:11080";

/// Переменные окружения, которые читаются как fallback.
const ENV_CONFIG: &str = "OBSISTENT_CONFIG";
const ENV_DATABASE: &str = "OBSISTENT_DATABASE";
// ---
/// Сырые переопределения путей, полученные из CLI / ENV.
/// Разбираются один раз в `main` через [`parse_cli`] и передаются дальше.
/// Поля приватные — снаружи структура непрозрачна.
#[derive(Debug, Default, Clone)]
pub struct PathOverrides {
    /// Путь до `config.toml` (CLI или ENV).
    config: Option<String>,
    /// Database URL (CLI или ENV).
    database: Option<String>,
    /// Запрошен ли `--init` (генерация шаблона и открытие в редакторе).
    init: bool,
    /// Запрошен ли `--verbose` (подробный вывод).
    verbose: bool,
    /// Запрошен ли `--allow-autogenerated` (стартовать с неотредактированным
    /// шаблоном конфига, игнорируя `autogenerated = true`).
    allow_autogenerated: bool,
    /// Запрошен ли `--print-config` (после `--print-config` нужно выйти).
    print_config: bool,
    /// Запрошен ли `--help` / `-h`.
    help: bool,
}

impl PathOverrides {
    /// Запрошен ли `--help` / `-h`.
    pub fn help(&self) -> bool {
        self.help
    }

    /// Запрошен ли `--init`.
    pub fn init(&self) -> bool {
        self.init
    }
}

/// Распечатать краткую справку по аргументам командной строки.
pub fn print_help() {
    println!(
        "ObScape - AI core for your project.\n\n\
          Usage:\n  \
              obscape-server [OPTIONS]\n\n\
          Options:\n  \
              --config <PATH>       Path to config.toml (default: {DEFAULT})\n  \
              --database <URL>      Database URL (overrides the config.toml value)\n  \
              --init                Generate a config template and open it in an editor\n  \
              --verbose             Verbose logging\n  \
              --allow-autogenerated Start even if config.toml is an unedited template\n  \
              --print-config        Print the resulting Config (for debugging) and exit\n  \
              -h, --help            Show this help and exit\n\n\
          Environment variables:\n  \
              {ENV_CONFIG}            Same as --config\n  \
              {ENV_DATABASE}          Same as --database\n",
        DEFAULT = make_file_path().unwrap_or_else(|_| "~/.config/obscape/config.toml".to_string()),
        ENV_CONFIG = ENV_CONFIG,
        ENV_DATABASE = ENV_DATABASE,
    );
}

/// Разобрать `argv` и ENV один раз. Единственная точка входа для CLI.
pub fn parse_cli() -> Result<PathOverrides, ConfigError> {
    parse_args(
        env::args().skip(1),
        env::var(ENV_CONFIG).ok(),
        env::var(ENV_DATABASE).ok(),
    )
}

/// Разобрать `argv` (без имени программы) в `PathOverrides`.
/// `env_config` / `env_database` — значения `ENV_CONFIG` / `ENV_DATABASE`,
/// переданы параметрами, чтобы функцию можно было тестировать без
/// глобального окружения.
fn parse_args<I>(
    args: I,
    env_config: Option<String>,
    env_database: Option<String>,
) -> Result<PathOverrides, ConfigError>
where
    I: IntoIterator<Item = String>,
{
    let mut out = PathOverrides::default();
    let mut it = args.into_iter();
    while let Some(arg) = it.next() {
        match arg.as_str() {
            "-h" | "--help" => out.help = true,
            "--init" => out.init = true,
            "--verbose" => out.verbose = true,
            "--allow-autogenerated" => out.allow_autogenerated = true,
            "--print-config" => out.print_config = true,
            "--config" => {
                out.config = Some(next_value(&mut it, "--config")?);
            }
            "--database" => {
                out.database = Some(next_value(&mut it, "--database")?);
            }
            other if other.starts_with("--config=") => {
                out.config = Some(strip_eq(other, "--config="));
            }
            other if other.starts_with("--database=") => {
                out.database = Some(strip_eq(other, "--database="));
            }
            other => {
                return Err(ConfigError::InvalidArgs(format!(
                    "unknown argument: `{other}` (try --help)"
                )));
            }
        }
    }

    // Если путь до конфига не задан через CLI — пробуем ENV.
    if out.config.is_none()
        && let Some(v) = env_config
        && !v.is_empty()
    {
        out.config = Some(v);
    }
    // То же для database.
    if out.database.is_none()
        && let Some(v) = env_database
        && !v.is_empty()
    {
        out.database = Some(v);
    }
    Ok(out)
}

fn next_value<I: Iterator<Item = String>>(it: &mut I, flag: &str) -> Result<String, ConfigError> {
    it.next()
        .ok_or_else(|| ConfigError::InvalidArgs(format!("flag `{flag}` requires a value")))
}

fn strip_eq(arg: &str, prefix: &str) -> String {
    arg[prefix.len()..].to_string()
}

/// Похоже ли, что мы внутри контейнера (Docker/Podman/containerd/k8s).
/// Не пытается быть безупречным — это эвристика для одной цели:
/// не пытаться открыть графический редактор там, где его точно нет.
pub fn is_containerized() -> bool {
    // Явный override — на случай нестандартных раннеров (CI, gVisor,
    // rootless-контейнеры), которые эвристики ниже не ловят.
    if env::var("OBSISTENT_NO_EDITOR").is_ok_and(|v| v == "1" || v.eq_ignore_ascii_case("true")) {
        return true;
    }

    // Классический маркер, который Docker кладёт в контейнер.
    if std::path::Path::new("/.dockerenv").exists() {
        return true;
    }

    // systemd-nspawn / некоторые CI-раннеры выставляют это.
    if env::var("container").is_ok() {
        return true;
    }

    // cgroup-путь процесса #1 обычно содержит "docker"/"kubepods"/"containerd"
    // внутри контейнера и не содержит — на голом хосте.
    if let Ok(cgroup) = fs::read_to_string("/proc/1/cgroup")
        && (cgroup.contains("docker")
            || cgroup.contains("kubepods")
            || cgroup.contains("containerd"))
    {
        return true;
    }

    false
}

pub fn resolve_config_path(overrides: &PathOverrides) -> Result<String, ConfigError> {
    match &overrides.config {
        Some(p) => Ok(p.clone()),
        None => make_conf_path(),
    }
}

/// Загрузить конфиг с учётом CLI-аргументов и ENV.
/// Приоритет: CLI > ENV > значение из config.toml.
pub fn load_config(overrides: &PathOverrides) -> Result<Config, ConfigError> {
    let mut conf_path = resolve_config_path(overrides)?;
    conf_path = format_conf_path(conf_path);

    // 2. Читаем и парсим TOML.
    let contents = fs::read_to_string(&conf_path).map_err(ConfigError::Io)?;
    let mut config: Config = toml::from_str(&contents).map_err(ConfigError::Parse)?;

    if overrides.allow_autogenerated {
        config.autogenerated = false;
    }
    if config.autogenerated {
        // Редактор открываем только вне контейнера; отказ от старта —
        // в любом случае.
        if !is_containerized() {
            #[cfg(target_os = "windows")]
            {
                let _ = std::process::Command::new("notepad")
                    .arg(&conf_path)
                    .spawn();
            }
            #[cfg(not(target_os = "windows"))]
            {
                let _ = std::process::Command::new("xdg-open")
                    .arg(&conf_path)
                    .spawn();
            }
        }
        return Err(ConfigError::Autogenerated);
    }

    // 3. Применяем override для database (CLI > ENV > config.toml).
    if let Some(database) = &overrides.database {
        config.database_url = database.clone();
    }
    if overrides.verbose {
        config.verbose = true;
    }

    // 4. Пост-валидация критичных полей.
    if config.database_url.trim().is_empty() {
        return Err(ConfigError::MissingField("database_url"));
    }
    let mut mains: Vec<&String> = config
        .agents
        .iter()
        .filter(|(_, a)| a.enabled && a.main)
        .map(|(name, _)| name)
        .collect();
    if mains.len() > 1 {
        mains.sort();
        return Err(ConfigError::Invalid(format!(
            "more than one enabled agent has `main = true`: {}",
            mains
                .iter()
                .map(|s| s.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        )));
    }
    // 5. Дефолт для http_bind, если в config.toml не задан.
    if config
        .http_bind
        .as_deref()
        .map(str::trim)
        .map(str::is_empty)
        .unwrap_or(true)
    {
        config.http_bind = Some(DEFAULT_HTTP_BIND.to_string());
    }

    if overrides.print_config {
        print_config(&config);
        std::process::exit(0);
    }

    Ok(config)
}

pub fn init_config(overrides: &PathOverrides) -> Result<(), ConfigError> {
    let mut path = resolve_config_path(overrides)?;
    if !fs::exists(&path).map_err(ConfigError::Io)? {
        fs::create_dir_all(&path).map_err(ConfigError::Io)?;
    }
    path = format_conf_path(path);
    let mut file = fs::File::create_new(&path).map_err(ConfigError::Io)?;

    let template = r#"
autogenerated = true
database_url = "postgres://user:pass@localhost:5432/obscape"
http_bind = "0.0.0.0:11080"
verbose = false
shared_prompt = "You are a helpful assistant. Say hello to user."
# Сколько последних сообщений чата отправлять модели (системный промпт не считается).
history_limit = 50

[agents.primary]
enabled = true
# Агент по умолчанию для POST /v1/chat/new без поля `agent`.
main = true
model_id = "Gemma4-E2B"
api_url = "https://example.com/v1/"
api_key = "abc123"
personality_prompt = "Your name is Paul. You must write using only low letters."
# Таймаут запроса к модели в секундах.
timeout_secs = 120
        "#;

    file.write_all(template.as_bytes())
        .map_err(ConfigError::Io)?;
    println!("Config template created: {}", path);

    if !is_containerized() {
        #[cfg(target_os = "windows")]
        {
            let _ = std::process::Command::new("notepad").arg(&path).spawn();
        }
        #[cfg(not(target_os = "windows"))]
        {
            let _ = std::process::Command::new("xdg-open").arg(&path).spawn();
        }
    }

    Ok(())
}

/// Pretty-print конфигурации для `--print-config`.
pub fn print_config(config: &Config) {
    let mut agents_list = Vec::new();
    for (name, aconfig) in &config.agents {
        if aconfig.enabled {
            agents_list.push(name);
        }
    }

    println!("database_url  = {}", mask_db_password(&config.database_url));
    println!(
        "http_bind     = {}",
        config.http_bind.as_deref().unwrap_or(DEFAULT_HTTP_BIND)
    );
    println!("verbose       = {}", config.verbose);
    println!("history_limit = {}", config.history_limit);
    println!("shared_prompt = {}", config.shared_prompt);
    println!("enabled agents = {:#?}", agents_list);
    println!(
        "main agent    = {}",
        config.main_agent().unwrap_or("(none)")
    );
}

/// Заменить пароль в URL вида `scheme://user:pass@host/db` на `***`.
/// URL без пароля (или без authority) возвращается как есть.
pub fn mask_db_password(url: &str) -> String {
    let Some((scheme, rest)) = url.split_once("://") else {
        return url.to_string();
    };
    let Some((userinfo, host)) = rest.split_once('@') else {
        return url.to_string();
    };
    match userinfo.split_once(':') {
        Some((user, _)) => format!("{scheme}://{user}:***@{host}"),
        None => url.to_string(),
    }
}

/// Удобство для `main()`: вернуть код возврата в зависимости от того,
/// попросил ли пользователь `--help` / `--print-config`.
/// Возвращаем `i32`, чтобы `std::process::exit` мог принять значение
/// и на stable Rust (где `ExitCode::process` недоступен).
pub fn dispatch_cli(overrides: &PathOverrides) -> Result<Config, i32> {
    match load_config(overrides) {
        Ok(cfg) => Ok(cfg),
        Err(e) => {
            eprintln!("{e}");
            Err(2)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{ConfigError, PathOverrides, mask_db_password, parse_args};

    fn parse(args: &[&str]) -> Result<PathOverrides, ConfigError> {
        parse_args(args.iter().map(|s| s.to_string()), None, None)
    }

    #[test]
    fn parses_all_flags() {
        let o = parse(&[
            "--config",
            "/etc/obscape",
            "--database",
            "postgres://x",
            "--init",
            "--verbose",
            "--allow-autogenerated",
            "--print-config",
            "-h",
        ])
        .unwrap();
        assert_eq!(o.config.as_deref(), Some("/etc/obscape"));
        assert_eq!(o.database.as_deref(), Some("postgres://x"));
        assert!(o.init && o.verbose && o.allow_autogenerated && o.print_config && o.help);
    }

    #[test]
    fn parses_equals_form_and_long_help() {
        let o = parse(&["--config=/a", "--database=pg://b", "--help"]).unwrap();
        assert_eq!(o.config.as_deref(), Some("/a"));
        assert_eq!(o.database.as_deref(), Some("pg://b"));
        assert!(o.help);
    }

    #[test]
    fn empty_args_give_defaults() {
        let o = parse(&[]).unwrap();
        assert!(o.config.is_none() && o.database.is_none());
        assert!(!o.init && !o.verbose && !o.allow_autogenerated && !o.print_config && !o.help);
    }

    #[test]
    fn rejects_unknown_argument() {
        match parse(&["--bogus"]) {
            Err(ConfigError::InvalidArgs(msg)) => assert!(msg.contains("--bogus")),
            other => panic!("expected InvalidArgs, got {other:?}"),
        }
    }

    #[test]
    fn rejects_flag_without_value() {
        assert!(matches!(
            parse(&["--config"]),
            Err(ConfigError::InvalidArgs(_))
        ));
        assert!(matches!(
            parse(&["--database"]),
            Err(ConfigError::InvalidArgs(_))
        ));
    }

    #[test]
    fn env_is_fallback_only() {
        let args = |a: &[&str]| a.iter().map(|s| s.to_string()).collect::<Vec<_>>();
        let o = parse_args(args(&[]), Some("/env".into()), Some("pg://env".into())).unwrap();
        assert_eq!(o.config.as_deref(), Some("/env"));
        assert_eq!(o.database.as_deref(), Some("pg://env"));

        let o = parse_args(
            args(&["--config=/cli"]),
            Some("/env".into()),
            Some(String::new()),
        )
        .unwrap();
        assert_eq!(o.config.as_deref(), Some("/cli"));
        assert!(o.database.is_none(), "empty env value must be ignored");
    }

    #[test]
    fn masks_password() {
        assert_eq!(
            mask_db_password("postgres://user:s3cret@localhost:5432/obscape"),
            "postgres://user:***@localhost:5432/obscape"
        );
    }

    #[test]
    fn keeps_url_without_password() {
        assert_eq!(
            mask_db_password("postgres://user@localhost/db"),
            "postgres://user@localhost/db"
        );
        assert_eq!(
            mask_db_password("postgres://localhost/db"),
            "postgres://localhost/db"
        );
    }

    #[test]
    fn masks_password_containing_at() {
        // Незакодированный `@` в пароле — главное, что пароль не утекает.
        assert!(!mask_db_password("postgres://u:p@ss@h/db").contains("p@ss"));
    }
}
