use serde::Deserialize;
use std::env;
use std::fs;
use std::io::Write;

#[derive(Debug, Deserialize, Clone)]
pub struct AgentConfig {
    pub enabled: bool,
    pub main: bool,
    pub model_id: String,
    pub api_url: String,
    pub api_key: String,
    pub personality_prompt: String,
}
impl AgentConfig {
    pub fn merge_config(&self, shared: &str) -> String {
        format!("{} {}", shared, self.personality_prompt)
    }
}
#[derive(Debug, Deserialize, Clone)]
pub struct Config {
    pub autogenerated: bool,
    pub database_url: String,
    /// Адрес и порт HTTP-сервера (например, `0.0.0.0:11080`).
    /// `None` означает "использовать дефолт".
    pub http_bind: Option<String>,
    pub verbose: bool,
    pub shared_prompt: String,
    pub agents: std::collections::HashMap<String, AgentConfig>,
}

/// Ошибки загрузки/парсинга конфигурации.
#[derive(Debug)]
pub enum ConfigError {
    Autogenerated,
    Io(std::io::Error),
    Parse(toml::de::Error),
    MissingField(&'static str),
    InvalidArgs(String),
}

impl std::fmt::Display for ConfigError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ConfigError::Autogenerated => write!(f, "Config is autogenerated. Redact it firstly."),
            ConfigError::Io(e) => write!(f, "failed to read config: {e}"),
            ConfigError::Parse(e) => write!(f, "failed to parse TOML: {e}"),
            ConfigError::MissingField(name) => write!(f, "missing field `{name}` in config"),
            ConfigError::InvalidArgs(msg) => write!(f, "{msg}"),
        }
    }
}

impl std::error::Error for ConfigError {}

/// Дефолтный путь до файла конфигурации.
fn make_conf_path() -> String {
    let home = env::home_dir().unwrap().into_string().unwrap();
    let out = format!("{}/.config/obscape", home);
    dbg!(&out);
    out
}

pub fn make_file_path() -> String {
    format!("{}/config.toml", make_conf_path())
}

/// Дефолтный адрес HTTP-сервера.
const DEFAULT_HTTP_BIND: &str = "0.0.0.0:11080";

/// Переменные окружения, которые читаются как fallback.
const ENV_CONFIG: &str = "OBSISTENT_CONFIG";
const ENV_DATABASE: &str = "OBSISTENT_DATABASE";
// ---
/// Сырые переопределения путей, полученные из CLI / ENV.
#[derive(Debug, Default, Clone)]
struct PathOverrides {
    /// Путь до `config.toml` (CLI или ENV).
    config: Option<String>,
    /// Database URL (CLI или ENV).
    database: Option<String>,
    /// Запрошен ли `--init` (генерация шаблона и открытие в редакторе).
    init: bool,
    /// Запрошен ли `--verbose` (подробный вывод).
    verbose: bool,
    /// Запрошен ли `--print-config` (после `--print-config` нужно выйти).
    print_config: bool,
    /// Запрошен ли `--help` / `-h`.
    help: bool,
}

/// Распечатать краткую справку по аргументам командной строки.
pub fn print_help() {
    println!(
        "ObScape - AI core for your project.\n\n\
          Usage:\n  \
              obscape-server [OPTIONS]\n\n\
          Options:\n  \
              --config <PATH>       Path to config.toml (default: {DEFAULT})\n  \
              --database <URL>      Database URL (overrides the config.toml value)\n  \
              --init                Generate a config template and open it in an editor\n  \
              --verbose             Verbose logging\n  \
              --print-config        Print the resulting Config (for debugging) and exit\n  \
              -h, --help            Show this help and exit\n\n\
          Environment variables:\n  \
              {ENV_CONFIG}            Same as --config\n  \
              {ENV_DATABASE}          Same as --database\n",
        DEFAULT = make_conf_path(),
        ENV_CONFIG = ENV_CONFIG,
        ENV_DATABASE = ENV_DATABASE,
    );
}

/// Разобрать `argv` (без имени программы) в `PathOverrides`.
fn parse_args() -> Result<PathOverrides, ConfigError> {
    let mut out = PathOverrides::default();
    let mut it = env::args().skip(1);
    while let Some(arg) = it.next() {
        match arg.as_str() {
            "-h" | "--help" => out.help = true,
            "--init" => out.init = true,
            "--verbose" => out.verbose = true,
            "--config" => {
                out.config = Some(next_value(&mut it, "--config")?);
            }
            "--database" => {
                out.database = Some(next_value(&mut it, "--database")?);
            }
            other if other.starts_with("--config=") => {
                out.config = Some(strip_eq(other, "--config="));
            }
            other if other.starts_with("--database=") => {
                out.database = Some(strip_eq(other, "--database="));
            }
            other => {
                return Err(ConfigError::InvalidArgs(format!(
                    "unknown argument: `{other}` (try --help)"
                )));
            }
        }
    }

    // Если путь до конфига не задан через CLI — пробуем ENV.
    if out.config.is_none()
        && let Ok(v) = env::var(ENV_CONFIG)
        && !v.is_empty()
    {
        out.config = Some(v);
    }
    // То же для database.
    if out.database.is_none()
        && let Ok(v) = env::var(ENV_DATABASE)
        && !v.is_empty()
    {
        out.database = Some(v);
    }
    Ok(out)
}

fn next_value<I: Iterator<Item = String>>(it: &mut I, flag: &str) -> Result<String, ConfigError> {
    it.next()
        .ok_or_else(|| ConfigError::InvalidArgs(format!("flag `{flag}` requires a value")))
}

fn strip_eq(arg: &str, prefix: &str) -> String {
    arg[prefix.len()..].to_string()
}

/// Загрузить конфиг с учётом CLI-аргументов и ENV.
///
/// Приоритет: CLI > ENV > значение из config.toml.
pub fn load_config() -> Result<Config, ConfigError> {
    let conf_path = make_file_path();
    dbg!(&conf_path);
    let overrides = parse_args()?;

    if overrides.help {
        print_help();
        std::process::exit(0);
    }

    if overrides.init {
        init_config()?;
        std::process::exit(0);
    }

    // 2. Читаем и парсим TOML.
    let contents = fs::read_to_string(&conf_path).map_err(ConfigError::Io)?;
    let mut config: Config = toml::from_str(&contents).map_err(ConfigError::Parse)?;

    if overrides.verbose || config.verbose {
        config.autogenerated = false;
    }
    if config.autogenerated {
        #[cfg(target_os = "windows")]
        {
            let _ = std::process::Command::new("notepad")
                .arg(&config_path)
                .spawn();
        }
        #[cfg(not(target_os = "windows"))]
        {
            let _ = std::process::Command::new("xdg-open")
                .arg(&conf_path)
                .spawn();
        }
        return Err(ConfigError::Autogenerated);
    }

    // 3. Применяем override для database (CLI > ENV > config.toml).
    if let Some(database) = overrides.database {
        config.database_url = database;
    }
    if overrides.verbose {
        config.verbose = true;
    }

    // 4. Пост-валидация критичных полей.
    if config.database_url.trim().is_empty() {
        return Err(ConfigError::MissingField("database_url"));
    }
    // 5. Дефолт для http_bind, если в config.toml не задан.
    if config
        .http_bind
        .as_deref()
        .map(str::trim)
        .map(str::is_empty)
        .unwrap_or(true)
    {
        config.http_bind = Some(DEFAULT_HTTP_BIND.to_string());
    }

    if overrides.print_config {
        print_config(&config);
        std::process::exit(0);
    }

    Ok(config)
}

pub fn init_config() -> Result<(), ConfigError> {
    let path = make_file_path();
    let mut file = fs::File::create(&path).map_err(ConfigError::Io)?;

    let template = r#"
        autogenerated = true
        database_url = "postgres://user:pass@localhost:5432/obscape"
        http_bind = "0.0.0.0:11080"
        verbose = false
        shared_prompt = "You are a helpful assistant. Say hello to user."

        [agents.primary]
        enabled = true
        main = true
        model_id = "Gemma4-E2B"
        api_url = "https://example.com/v1/"
        api_key = "abc123"
        personality_prompt = "Your name is Paul. You must write using only low letters."
        "#;

    file.write_all(template.as_bytes())
        .map_err(ConfigError::Io)?;
    println!("Config template created: {}", path);

    #[cfg(target_os = "windows")]
    {
        let _ = std::process::Command::new("notepad").arg(&path).spawn();
    }
    #[cfg(not(target_os = "windows"))]
    {
        let _ = std::process::Command::new("xdg-open").arg(&path).spawn();
    }

    Ok(())
}

/// Pretty-print конфигурации для `--print-config`.
pub fn print_config(config: &Config) {
    let mut agents_list = Vec::new();
    for (name, aconfig) in &config.agents {
        if aconfig.enabled {
            agents_list.push(name);
        }
    }

    println!("database_url  = {}", config.database_url);
    println!(
        "http_bind     = {}",
        config.http_bind.as_deref().unwrap_or(DEFAULT_HTTP_BIND)
    );
    println!("verbose       = {}", config.verbose);
    println!("shared_prompt = {}", config.shared_prompt);
    println!("enabled agents = {:#?}", agents_list);
}

/// Удобство для `main()`: вернуть код возврата в зависимости от того,
/// попросил ли пользователь `--help` / `--print-config`.
/// Возвращаем `i32`, чтобы `std::process::exit` мог принять значение
/// и на stable Rust (где `ExitCode::process` недоступен).
pub fn dispatch_cli() -> Result<Config, i32> {
    match load_config() {
        Ok(cfg) => Ok(cfg),
        Err(e) => {
            eprintln!("{e}");
            Err(2)
        }
    }
}
